"""initial schema

Revision ID: b38117986837
Revises: 
Create Date: 2026-09-22 11:31:56.930963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38117986837'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counters',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('large_party_enquiries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('venueId', sa.String(), nullable=False),
    sa.Column('guestName', sa.String(), nullable=False),
    sa.Column('partySize', sa.Integer(), nullable=False),
    sa.Column('mobileNumber', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entryId', sa.String(), nullable=True),
    sa.Column('recipientType', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('templateType', sa.String(), nullable=False),
    sa.Column('renderedMessage', sa.String(), nullable=False),
    sa.Column('deliveryStatus', sa.String(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=False),
    sa.Column('sentAt', sa.String(), nullable=True),
    sa.Column('errorMessage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('staffName', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('minCapacity', sa.Integer(), nullable=False),
    sa.Column('maxCapacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('availabilityState', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('occupyingTicketCode', sa.String(), nullable=True),
    sa.Column('occupyingEntryId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logoPlaceholderLabel', sa.String(), nullable=False),
    sa.Column('contactPhone', sa.String(), nullable=False),
    sa.Column('staffNotificationEmail', sa.String(), nullable=False),
    sa.Column('menuUrl', sa.String(), nullable=False),
    sa.Column('maxOnlinePartySize', sa.Integer(), nullable=False),
    sa.Column('gracePeriodMinutes', sa.Integer(), nullable=False),
    sa.Column('entryMode', sa.String(), nullable=False),
    sa.Column('waitlistOpen', sa.Boolean(), nullable=False),
    sa.Column('defaultWaitEstimateMinutes', sa.JSON(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('serviceDate', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waitlist_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venueId', sa.String(), nullable=False),
    sa.Column('serviceDate', sa.String(), nullable=False),
    sa.Column('ticketCode', sa.String(), nullable=False),
    sa.Column('ticketSequence', sa.Integer(), nullable=False),
    sa.Column('guestName', sa.String(), nullable=False),
    sa.Column('partySize', sa.Integer(), nullable=False),
    sa.Column('originalPartySize', sa.Integer(), nullable=False),
    sa.Column('originalPartyClass', sa.String(), nullable=False),
    sa.Column('currentSeatingClass', sa.String(), nullable=False),
    sa.Column('reviewRequired', sa.Boolean(), nullable=False),
    sa.Column('reviewReason', sa.String(), nullable=True),
    sa.Column('mobileNumber', sa.String(), nullable=False),
    sa.Column('seatingNote', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('arrivalTime', sa.String(), nullable=False),
    sa.Column('estimatedWaitMinutes', sa.Integer(), nullable=False),
    sa.Column('notifiedAt', sa.String(), nullable=True),
    sa.Column('returnByAt', sa.String(), nullable=True),
    sa.Column('seatedAt', sa.String(), nullable=True),
    sa.Column('completedAt', sa.String(), nullable=True),
    sa.Column('cancelledAt', sa.String(), nullable=True),
    sa.Column('tableId', sa.String(), nullable=True),
    sa.Column('tableName', sa.String(), nullable=True),
    sa.Column('seatingOverrideReason', sa.String(), nullable=True),
    sa.Column('accessToken', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accessToken')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waitlist_entries')
    op.drop_table('venues')
    op.drop_table('tables')
    op.drop_table('staff_users')
    op.drop_table('notifications')
    op.drop_table('large_party_enquiries')
    op.drop_table('counters')
    # ### end Alembic commands ###
